//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""ShipControls"",
            ""id"": ""284d2e07-210e-43b7-acf0-dc0945d5fecc"",
            ""actions"": [
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""a5f95b34-3769-4c3d-a6e1-07e47f806d53"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8ec09660-dc23-4140-bfd1-0dcae25f4f67"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""6ec16057-3c3f-4f5d-9ff5-31a3f0444892"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Value"",
                    ""id"": ""a194c0e6-6dd6-42d0-805b-eb1731492977"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""193c3d67-5808-4d3e-97c4-3e141e5c9671"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenQT"",
                    ""type"": ""Button"",
                    ""id"": ""ada60fca-fbc9-4b82-b240-bae61e975a8d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenWeapons"",
                    ""type"": ""Button"",
                    ""id"": ""bfb280b3-dcce-48e9-a936-6344404c8047"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WSlotSelect1"",
                    ""type"": ""Button"",
                    ""id"": ""e0daebed-0aac-47f8-9fd8-82569d5cf8fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WSlotSelect2"",
                    ""type"": ""Button"",
                    ""id"": ""db155ada-798e-4b84-96c0-1d04a0d4b621"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WSlotSelect3"",
                    ""type"": ""Button"",
                    ""id"": ""79e777ce-f370-4500-88d4-857872103c9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponAction"",
                    ""type"": ""Button"",
                    ""id"": ""337e65af-a8ff-448f-a03b-8f712b87ef41"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""939cca1c-1886-47ef-9f54-aa920de75127"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f6cf2b51-025e-490b-b1b4-af3c79f90e52"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1af6db04-85c8-4c1f-9a79-c40c01c4b7de"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e350cae8-f288-47bd-8711-20d4bbdc6af8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""607e09b5-0868-4ddc-b6f8-d0fda4c328fa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""71c190bb-a207-49f3-b8e0-df180d1380a0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""245d7f76-a4d9-4ecc-864e-5dd05f9285ed"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bb349223-25eb-4799-a451-5d214a3be53e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""029ed901-2d46-49a1-972f-4f2f4afe5107"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6ea586db-ad2f-4fca-a964-29d92af280ff"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""56c67acd-093b-4fb7-8022-1c019d558803"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88eeb35a-0a72-42ea-acba-44d9f726c533"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""699f6044-260a-4529-986f-d1ee2af3b91b"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenQT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de78a5ea-a89c-4f8d-8fdd-d83971f92504"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenWeapons"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f50b4ba-7f8c-4324-a997-eeb51fd49087"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e7e1750-5a3b-4b4b-b330-53d40986c7c4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WSlotSelect1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8cadd8a-3937-43b5-8cf6-82e32d39e29b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WSlotSelect2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdcbb7b2-03cb-466a-a218-6678f0e1b1f2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WSlotSelect3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""617afbfe-bec9-4681-a115-f6cd275cec84"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""9e1769db-6cba-4814-904a-6f3d300d36f8"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""e2ac8e61-4018-4a52-bf4a-e72f2a1f811b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelQT"",
                    ""type"": ""Button"",
                    ""id"": ""1a6dbfac-940d-419f-b0d8-ab114c73e5a5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84ebf60f-bebf-44dd-883c-8c02cfd5378a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3db32567-4271-4659-8852-1516a63c5cc2"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelQT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ShipControls
        m_ShipControls = asset.FindActionMap("ShipControls", throwIfNotFound: true);
        m_ShipControls_Debug = m_ShipControls.FindAction("Debug", throwIfNotFound: true);
        m_ShipControls_Move = m_ShipControls.FindAction("Move", throwIfNotFound: true);
        m_ShipControls_Rotate = m_ShipControls.FindAction("Rotate", throwIfNotFound: true);
        m_ShipControls_Roll = m_ShipControls.FindAction("Roll", throwIfNotFound: true);
        m_ShipControls_Pause = m_ShipControls.FindAction("Pause", throwIfNotFound: true);
        m_ShipControls_OpenQT = m_ShipControls.FindAction("OpenQT", throwIfNotFound: true);
        m_ShipControls_OpenWeapons = m_ShipControls.FindAction("OpenWeapons", throwIfNotFound: true);
        m_ShipControls_WSlotSelect1 = m_ShipControls.FindAction("WSlotSelect1", throwIfNotFound: true);
        m_ShipControls_WSlotSelect2 = m_ShipControls.FindAction("WSlotSelect2", throwIfNotFound: true);
        m_ShipControls_WSlotSelect3 = m_ShipControls.FindAction("WSlotSelect3", throwIfNotFound: true);
        m_ShipControls_WeaponAction = m_ShipControls.FindAction("WeaponAction", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Close = m_UI.FindAction("Close", throwIfNotFound: true);
        m_UI_CancelQT = m_UI.FindAction("CancelQT", throwIfNotFound: true);
    }

    ~@GameInput()
    {
        UnityEngine.Debug.Assert(!m_ShipControls.enabled, "This will cause a leak and performance issues, GameInput.ShipControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, GameInput.UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShipControls
    private readonly InputActionMap m_ShipControls;
    private List<IShipControlsActions> m_ShipControlsActionsCallbackInterfaces = new List<IShipControlsActions>();
    private readonly InputAction m_ShipControls_Debug;
    private readonly InputAction m_ShipControls_Move;
    private readonly InputAction m_ShipControls_Rotate;
    private readonly InputAction m_ShipControls_Roll;
    private readonly InputAction m_ShipControls_Pause;
    private readonly InputAction m_ShipControls_OpenQT;
    private readonly InputAction m_ShipControls_OpenWeapons;
    private readonly InputAction m_ShipControls_WSlotSelect1;
    private readonly InputAction m_ShipControls_WSlotSelect2;
    private readonly InputAction m_ShipControls_WSlotSelect3;
    private readonly InputAction m_ShipControls_WeaponAction;
    public struct ShipControlsActions
    {
        private @GameInput m_Wrapper;
        public ShipControlsActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Debug => m_Wrapper.m_ShipControls_Debug;
        public InputAction @Move => m_Wrapper.m_ShipControls_Move;
        public InputAction @Rotate => m_Wrapper.m_ShipControls_Rotate;
        public InputAction @Roll => m_Wrapper.m_ShipControls_Roll;
        public InputAction @Pause => m_Wrapper.m_ShipControls_Pause;
        public InputAction @OpenQT => m_Wrapper.m_ShipControls_OpenQT;
        public InputAction @OpenWeapons => m_Wrapper.m_ShipControls_OpenWeapons;
        public InputAction @WSlotSelect1 => m_Wrapper.m_ShipControls_WSlotSelect1;
        public InputAction @WSlotSelect2 => m_Wrapper.m_ShipControls_WSlotSelect2;
        public InputAction @WSlotSelect3 => m_Wrapper.m_ShipControls_WSlotSelect3;
        public InputAction @WeaponAction => m_Wrapper.m_ShipControls_WeaponAction;
        public InputActionMap Get() { return m_Wrapper.m_ShipControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShipControlsActions set) { return set.Get(); }
        public void AddCallbacks(IShipControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ShipControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShipControlsActionsCallbackInterfaces.Add(instance);
            @Debug.started += instance.OnDebug;
            @Debug.performed += instance.OnDebug;
            @Debug.canceled += instance.OnDebug;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @OpenQT.started += instance.OnOpenQT;
            @OpenQT.performed += instance.OnOpenQT;
            @OpenQT.canceled += instance.OnOpenQT;
            @OpenWeapons.started += instance.OnOpenWeapons;
            @OpenWeapons.performed += instance.OnOpenWeapons;
            @OpenWeapons.canceled += instance.OnOpenWeapons;
            @WSlotSelect1.started += instance.OnWSlotSelect1;
            @WSlotSelect1.performed += instance.OnWSlotSelect1;
            @WSlotSelect1.canceled += instance.OnWSlotSelect1;
            @WSlotSelect2.started += instance.OnWSlotSelect2;
            @WSlotSelect2.performed += instance.OnWSlotSelect2;
            @WSlotSelect2.canceled += instance.OnWSlotSelect2;
            @WSlotSelect3.started += instance.OnWSlotSelect3;
            @WSlotSelect3.performed += instance.OnWSlotSelect3;
            @WSlotSelect3.canceled += instance.OnWSlotSelect3;
            @WeaponAction.started += instance.OnWeaponAction;
            @WeaponAction.performed += instance.OnWeaponAction;
            @WeaponAction.canceled += instance.OnWeaponAction;
        }

        private void UnregisterCallbacks(IShipControlsActions instance)
        {
            @Debug.started -= instance.OnDebug;
            @Debug.performed -= instance.OnDebug;
            @Debug.canceled -= instance.OnDebug;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @OpenQT.started -= instance.OnOpenQT;
            @OpenQT.performed -= instance.OnOpenQT;
            @OpenQT.canceled -= instance.OnOpenQT;
            @OpenWeapons.started -= instance.OnOpenWeapons;
            @OpenWeapons.performed -= instance.OnOpenWeapons;
            @OpenWeapons.canceled -= instance.OnOpenWeapons;
            @WSlotSelect1.started -= instance.OnWSlotSelect1;
            @WSlotSelect1.performed -= instance.OnWSlotSelect1;
            @WSlotSelect1.canceled -= instance.OnWSlotSelect1;
            @WSlotSelect2.started -= instance.OnWSlotSelect2;
            @WSlotSelect2.performed -= instance.OnWSlotSelect2;
            @WSlotSelect2.canceled -= instance.OnWSlotSelect2;
            @WSlotSelect3.started -= instance.OnWSlotSelect3;
            @WSlotSelect3.performed -= instance.OnWSlotSelect3;
            @WSlotSelect3.canceled -= instance.OnWSlotSelect3;
            @WeaponAction.started -= instance.OnWeaponAction;
            @WeaponAction.performed -= instance.OnWeaponAction;
            @WeaponAction.canceled -= instance.OnWeaponAction;
        }

        public void RemoveCallbacks(IShipControlsActions instance)
        {
            if (m_Wrapper.m_ShipControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShipControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ShipControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShipControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShipControlsActions @ShipControls => new ShipControlsActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Close;
    private readonly InputAction m_UI_CancelQT;
    public struct UIActions
    {
        private @GameInput m_Wrapper;
        public UIActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Close => m_Wrapper.m_UI_Close;
        public InputAction @CancelQT => m_Wrapper.m_UI_CancelQT;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
            @CancelQT.started += instance.OnCancelQT;
            @CancelQT.performed += instance.OnCancelQT;
            @CancelQT.canceled += instance.OnCancelQT;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
            @CancelQT.started -= instance.OnCancelQT;
            @CancelQT.performed -= instance.OnCancelQT;
            @CancelQT.canceled -= instance.OnCancelQT;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IShipControlsActions
    {
        void OnDebug(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnOpenQT(InputAction.CallbackContext context);
        void OnOpenWeapons(InputAction.CallbackContext context);
        void OnWSlotSelect1(InputAction.CallbackContext context);
        void OnWSlotSelect2(InputAction.CallbackContext context);
        void OnWSlotSelect3(InputAction.CallbackContext context);
        void OnWeaponAction(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnClose(InputAction.CallbackContext context);
        void OnCancelQT(InputAction.CallbackContext context);
    }
}
